name: smartvision
description: "A new Flutter project"
publish_to: 'none'


version: 1.1.0+3

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  tflite_v2:
    path: ./myplugins/tflite_v2-1.0.0

  cupertino_icons: ^1.0.8
  flutter_tts: ^3.6.3
  speech_to_text: ^6.4.0
  camera: ^0.10.5+5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo3.png
    - assets/models/model.tflite
    - assets/models/labels.txt